import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        <header className="bg-white border-b border-gray-100 sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
            <Link href="/" className="text-xl font-bold text-indigo-600">
              ASAP <span className="text-gray-900 font-medium">Showcase</span>
            </Link>
            <nav className="flex space-x-8">
              <Link href="/" className="text-sm font-medium text-gray-600 hover:text-indigo-600 transition-colors">
                Inventory
              </Link>
              <Link href="/blog" className="text-sm font-medium text-gray-600 hover:text-indigo-600 transition-colors">
                Blog
              </Link>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
